version: "3.9"

services:
  web:
    container_name: "teamcity"
    image: "jetbrains/teamcity-server"
    networks:
      - "teamcity"
    privileged: true
    ports:
      - "8111:8111"
    restart: always
    volumes:
      - ./.logs:/opt/teamcity/logs
      - ./.data:/data/teamcity_server/datadir
      - /etc/localtime:/etc/localtime:ro

  agent:
    build:
      context: ./agent
      dockerfile: ./Dockerfile
    container_name: "teamcity-agent"
    image: "docker-teamcity-agent"
    networks:
      - "teamcity"
    privileged: true
    restart: always
    volumes:
      - ./.logs:/opt/agent/logs
      - ./.works:/opt/agent/work
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  teamcity: {}
